export default [
  {
    token: 'TGN-916079',
    mname: 'txgenEsDtTkn',
    owner: 'erd19sjessnnzgwulw926cpx6g5alsh403jrzwr57uuzrmuznwkeajaq9k8q2p',
    minted: '10000000000',
    burnt: '0',
    isPaused: false,
    canUpgrade: true,
    canMint: true,
    canBurn: true,
    canChangeOwner: false,
    canPause: true,
    canFreeze: true,
    canWipe: true,
  },
  {
    token: 'TTE-ae246a',
    mname: 'TitelTokenESDT',
    owner: 'erd1jdvk2gejvsddxvvzmk77gv4leqfpdsudt4jr3p5qk63cdect49ns2pwtt9',
    minted: '100',
    burnt: '0',
    isPaused: false,
    canUpgrade: true,
    canMint: false,
    canBurn: false,
    canChangeOwner: false,
    canPause: false,
    canFreeze: false,
    canWipe: false,
  },
];
