export default [
  {
    tokenIdentifier: 'TGN-916079',
    tokenName: 'txgenEsDtTkn',
    ownerAddress: 'erd19sjessnnzgwulw926cpx6g5alsh403jrzwr57uuzrmuznwkeajaq9k8q2p',
    mintedValue: '10000000000',
    burntValue: '0',
    isPaused: false,
    canUpgrade: true,
    canMint: true,
    canBurn: true,
    canChangeOwner: false,
    canPause: true,
    canFreeze: true,
    canWipe: true,
  },
  {
    tokenIdentifier: 'TTE-ae246a',
    tokenName: 'TitelTokenESDT',
    ownerAddress: 'erd1jdvk2gejvsddxvvzmk77gv4leqfpdsudt4jr3p5qk63cdect49ns2pwtt9',
    mintedValue: '100',
    burntValue: '0',
    isPaused: false,
    canUpgrade: true,
    canMint: false,
    canBurn: false,
    canChangeOwner: false,
    canPause: false,
    canFreeze: false,
    canWipe: false,
  },
];
