export default {
  _index: 'tps',
  _type: '_doc',
  _id: 'meta',
  _version: 34845,
  _seq_no: 55639,
  _primary_term: 1,
  found: true,
  _source: {
    liveTPS: 103,
    peakTPS: 858,
    nrOfShards: 5,
    nrOfNodes: 100,
    blockNumber: 6936,
    roundNumber: 8466,
    roundTime: 6,
    averageBlockTxCount: 465,
    lastBlockTxCount: 618,
    totalProcessedTxCount: 3231933,
    shardID: 0,
    averageTPS: null,
    currentBlockNonce: 0,
  },
};
