import {
  faChartBar,
  faCheckCircle,
  faCircleCheck as faShieldCheck,
  faCircleCheck,
  faCircleDot as faCircleBolt,
  faCircleDown as faDownRight,
  faCircleDown,
  faCircleUp as faUpRight,
  faCircleUp,
  faClock,
  faClone,
  faEnvelope,
  faEye,
  faFileAlt as faCommand,
  faFileAlt,
  faFileCode,
  faFlag as faFlagAlt,
  faThumbsUp as faHandHoldingHand,
  faHandshake,
  faHeart,
  faHourglass,
  faMoon as faSnooze,
  faQuestionCircle,
  faSquareCheck as faBadgeCheck,
  faSquareCheck as faHexagonCheck,
  faSquareMinus as faSquareV,
  faSquarePlus as faHexagonVerticalNft,
  faUser
} from '@fortawesome/free-regular-svg-icons';
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAnglesLeft,
  faAnglesRight,
  faAngleUp as faArrowToTop,
  faAngleUp,
  faArrowDown,
  faArrowRight,
  faArrowRightFromBracket as faArrowRightFromArc,
  faArrowUp,
  faArrowUpRightFromSquare as faArrowUpRight,
  faArrowUpRightFromSquare,
  faArrowsTurnToDots as faArrowProgress,
  faBan,
  faBridge,
  faBridge as faPersonToPortal,
  faBridge as faPersonFromPortal,
  faBars as faGrid,
  faBars as faGrid2,
  faCaretRight,
  faChartPie as faChartPieAlt,
  faChartPie as faChartPieSimple,
  faChartPie,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleExclamation as faDiamondExclamation,
  faCircleInfo as faSquareInfo,
  faCircleInfo,
  faCircleMinus,
  faCircleNotch as faSpinnerThird,
  faCircleNotch,
  faCirclePause,
  faCirclePlus as faCircleS,
  faCirclePlus,
  faCircleQuestion,
  faCircleXmark as faCircleX,
  faCity,
  faCode as faTerminal,
  faCode,
  faCogs,
  faCoins,
  faCube,
  faDiamond,
  faDollarSign,
  faDownLong as faDown,
  faEllipsis,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faFilter,
  faGavel,
  faGlobe,
  faHistory,
  faInfinity,
  faInfoCircle,
  faLayerGroup as faLayerPlus,
  faLayerGroup,
  faLeaf,
  faLink,
  faList as faListTree,
  faList,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faPalette,
  faPen,
  faPencil,
  faPlay,
  faPlus,
  faReceipt,
  faRepeat,
  faScissors,
  faSearch,
  faServer,
  faSpinner,
  faSquarePen,
  faStream,
  faSync,
  faTimes,
  faTrash,
  faTrophy,
  faUpLong as faUp,
  faUserCheck,
  faUserFriends,
  faUserLock,
  faUsers,
  faXmark as faClose,
  faWifi as faWifiSlash
} from '@fortawesome/free-solid-svg-icons';

export {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAnglesLeft,
  faAnglesRight,
  faAngleUp,
  faArrowDown,
  faArrowProgress,
  faArrowRight,
  faArrowRightFromArc,
  faArrowToTop,
  faArrowUp,
  faArrowUpRight,
  faArrowUpRightFromSquare,
  faBadgeCheck,
  faBan,
  faBridge,
  faCaretRight,
  faChartBar,
  faChartPie,
  faChartPieAlt,
  faChartPieSimple,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleBolt,
  faCircleCheck,
  faCircleDown,
  faCircleInfo,
  faCircleMinus,
  faCircleNotch,
  faCirclePause,
  faCirclePlus,
  faCircleQuestion,
  faCircleS,
  faCircleUp,
  faCircleX,
  faCity,
  faClock,
  faClone,
  faClose,
  faCode,
  faCogs,
  faCoins,
  faCommand,
  faCube,
  faDiamond,
  faDiamondExclamation,
  faDollarSign,
  faDown,
  faDownRight,
  faEllipsis,
  faEnvelope,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faEye,
  faFileAlt,
  faFileCode,
  faFilter,
  faFlagAlt,
  faGavel,
  faGlobe,
  faGrid,
  faGrid2,
  faHandHoldingHand,
  faHandshake,
  faHeart,
  faHexagonCheck,
  faHexagonVerticalNft,
  faHistory,
  faHourglass,
  faInfinity,
  faInfoCircle,
  faLayerGroup,
  faLayerPlus,
  faLeaf,
  faLink,
  faList,
  faListTree,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faPalette,
  faPen,
  faPencil,
  faPersonToPortal,
  faPersonFromPortal,
  faPlay,
  faPlus,
  faQuestionCircle,
  faReceipt,
  faRepeat,
  faScissors,
  faSearch,
  faServer,
  faShieldCheck,
  faSnooze,
  faSpinner,
  faSpinnerThird,
  faSquareInfo,
  faSquarePen,
  faSquareV,
  faStream,
  faSync,
  faTerminal,
  faTimes,
  faTrash,
  faTrophy,
  faUp,
  faUpRight,
  faUser,
  faUserCheck,
  faUserFriends,
  faUserLock,
  faUsers,
  faWifiSlash
};
