import {
  faChartBar,
  faCheckCircle,
  faCircleCheck as faShieldCheck,
  faCircleCheck,
  faCircleDot as faCircleBolt,
  faCircleDown as faDownRight,
  faCircleDown,
  faCircleUp as faUpRight,
  faCircleUp,
  faClock,
  faClone,
  faEnvelope,
  faEye,
  faFileAlt,
  faFileAlt as faCommand,
  faFileCode,
  faFlag as faFlagAlt,
  faHeart,
  faHourglass,
  faMoon as faSnooze,
  faQuestionCircle,
  faSquareCheck as faBadgeCheck,
  faSquareCheck as faHexagonCheck,
  faSquareMinus as faSquareV,
  faSquarePlus as faHexagonVerticalNft,
  faUser
} from '@fortawesome/free-regular-svg-icons';
import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp as faArrowToTop,
  faAngleUp,
  faAnglesLeft,
  faAnglesRight,
  faArrowDown,
  faArrowRight,
  faArrowUp,
  faArrowUpRightFromSquare as faArrowUpRight,
  faBan,
  faBars as faGrid,
  faBars as faGrid2,
  faCaretRight,
  faChartPie as faChartPieAlt,
  faChartPie,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleExclamation as faDiamondExclamation,
  faCircleInfo,
  faCircleInfo as faSquareInfo,
  faCircleMinus,
  faCircleNotch as faSpinnerThird,
  faCircleNotch,
  faCirclePlus,
  faCity,
  faCode as faTerminal,
  faCode,
  faCogs,
  faCoins,
  faCube,
  faDiamond,
  faDollarSign,
  faDownLong as faDown,
  faEllipsis,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faFilter,
  faGavel,
  faGlobe,
  faHistory,
  faInfinity,
  faInfoCircle,
  faLayerGroup as faLayerPlus,
  faLayerGroup,
  faLeaf,
  faLink,
  faList as faListTree,
  faList,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faPalette,
  faPen,
  faPencil,
  faPlay,
  faPlus,
  faReceipt,
  faRepeat,
  faSearch,
  faServer,
  faSpinner,
  faSquarePen,
  faStream,
  faSync,
  faTimes,
  faTrophy,
  faUpLong as faUp,
  faUserCheck,
  faUserFriends,
  faWifi as faWifiSlash,
  faUserLock
} from '@fortawesome/free-solid-svg-icons';

export {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAnglesLeft,
  faAnglesRight,
  faArrowDown,
  faArrowRight,
  faArrowToTop,
  faArrowUp,
  faArrowUpRight,
  faBadgeCheck,
  faBan,
  faCaretRight,
  faChartBar,
  faChartPie,
  faChartPieAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleBolt,
  faCircleCheck,
  faCircleDown,
  faCircleInfo,
  faSquareInfo,
  faCircleMinus,
  faCircleNotch,
  faCirclePlus,
  faCircleUp,
  faCity,
  faClock,
  faClone,
  faCode,
  faCogs,
  faCoins,
  faCommand,
  faCube,
  faDiamond,
  faDiamondExclamation,
  faDollarSign,
  faDown,
  faDownRight,
  faEllipsis,
  faEnvelope,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faEye,
  faFileAlt,
  faFileCode,
  faFilter,
  faFlagAlt,
  faGavel,
  faGlobe,
  faGrid,
  faGrid2,
  faHeart,
  faHexagonCheck,
  faHexagonVerticalNft,
  faHistory,
  faHourglass,
  faInfinity,
  faInfoCircle,
  faLayerGroup,
  faLayerPlus,
  faLeaf,
  faLink,
  faList,
  faListTree,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faPalette,
  faPen,
  faPencil,
  faPlay,
  faPlus,
  faQuestionCircle,
  faReceipt,
  faRepeat,
  faSearch,
  faServer,
  faShieldCheck,
  faSnooze,
  faSpinner,
  faSpinnerThird,
  faSquarePen,
  faSquareV,
  faStream,
  faSync,
  faTerminal,
  faTimes,
  faTrophy,
  faUp,
  faUpRight,
  faUser,
  faUserCheck,
  faUserFriends,
  faUserLock,
  faWifiSlash
};
