import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAnglesLeft,
  faAnglesRight,
  faAngleUp,
  faAngleUp as faArrowToTop,
  faSquareCheck as faBadgeCheck,
  faBan,
  faCaretRight,
  faChartPie,
  faChartPie as faChartPieAlt,
  faCheck,
  faCheckCircle,
  faChevronRight,
  faCircleDot as faCircleBolt,
  faCircleCheck,
  faCircleDown,
  faCircleMinus,
  faCirclePlus,
  faCircleUp,
  faCode,
  faCogs,
  faCoins,
  faDollarSign,
  faExclamationTriangle,
  faFileAlt,
  faFilter,
  faBars as faGrid,
  faBars as faGrid2,
  faHeart,
  faSquareCheck as faHexagonCheck,
  faSquarePlus as faHexagonVerticalNft,
  faHourglass,
  faLayerGroup,
  faLeaf,
  faLink,
  faLock,
  faMapMarkerAlt,
  faReceipt,
  faServer,
  faCircleCheck as faShieldCheck,
  faSquarePen,
  faSquareMinus as faSquareV,
  faStream,
  faTimes,
  faUser,
  faUserCheck,
  faUserFriends
} from '@fortawesome/free-solid-svg-icons';

export {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAnglesLeft,
  faAnglesRight,
  faAngleUp,
  faArrowToTop,
  faBadgeCheck,
  faBan,
  faCaretRight,
  faChartPie,
  faChartPieAlt,
  faCheck,
  faCheckCircle,
  faChevronRight,
  faCircleBolt,
  faCircleCheck,
  faCircleDown,
  faCircleMinus,
  faCirclePlus,
  faCircleUp,
  faCode,
  faCogs,
  faCoins,
  faDollarSign,
  faExclamationTriangle,
  faFileAlt,
  faFilter,
  faGrid,
  faGrid2,
  faHeart,
  faHexagonCheck,
  faHexagonVerticalNft,
  faHourglass,
  faLayerGroup,
  faLeaf,
  faLink,
  faLock,
  faMapMarkerAlt,
  faReceipt,
  faServer,
  faShieldCheck,
  faSquarePen,
  faSquareV,
  faStream,
  faTimes,
  faUser,
  faUserCheck,
  faUserFriends
};
