import {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAnglesLeft,
  faAnglesRight,
  faAngleUp as faArrowToTop,
  faAngleUp,
  faArrowDown,
  faArrowRight,
  faArrowRightFromBracket as faArrowRightFromArc,
  faArrowUp,
  faArrowUpRightFromSquare as faArrowUpRight,
  faArrowUpRightFromSquare,
  faBan,
  faBridge,
  faBridge as faPersonToPortal,
  faBridge as faPersonFromPortal,
  faBars as faGrid,
  faBars as faGrid2,
  faCaretRight,
  faChartBar,
  faChartPie as faChartPieAlt,
  faChartPie as faChartPieSimple,
  faChartPie,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck as faShieldCheck,
  faCircleCheck,
  faCircleDot as faCircleBolt,
  faCircleDown as faDownRight,
  faCircleDown,
  faCircleExclamation as faDiamondExclamation,
  faCircleInfo as faSquareInfo,
  faCircleInfo,
  faCircleMinus,
  faCircleNotch as faSpinnerThird,
  faCircleNotch,
  faCirclePause,
  faCirclePlus as faCircleS,
  faCirclePlus,
  faCircleQuestion,
  faCircleUp as faUpRight,
  faCircleUp,
  faCircleXmark as faCircleX,
  faCity,
  faClock,
  faClone,
  faCode as faTerminal,
  faCode,
  faCogs,
  faCoins,
  faCube,
  faDiamond,
  faDollarSign,
  faDownLong as faDown,
  faEllipsis,
  faEnvelope,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faEye,
  faFileAlt as faCommand,
  faFileAlt,
  faFileCode,
  faFilter,
  faFlag as faFlagAlt,
  faGavel,
  faGlobe,
  faHeart,
  faHistory,
  faHourglass,
  faInfinity,
  faInfoCircle,
  faLayerGroup as faLayerPlus,
  faLayerGroup,
  faLeaf,
  faLink,
  faList as faListTree,
  faList,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faMoon as faSnooze,
  faPalette,
  faPen,
  faPencil,
  faPlay,
  faPlus,
  faQuestionCircle,
  faReceipt,
  faRepeat,
  faScissors,
  faSearch,
  faServer,
  faSpinner,
  faSquareCheck as faBadgeCheck,
  faSquareCheck as faHexagonCheck,
  faSquareMinus as faSquareV,
  faSquarePen,
  faSquarePlus as faHexagonVerticalNft,
  faStream,
  faSync,
  faTimes,
  faTrash,
  faTrophy,
  faUpLong as faUp,
  faUser,
  faUserCheck,
  faUserFriends,
  faUserLock,
  faXmark as faClose,
  faWifi as faWifiSlash
} from '@fortawesome/free-solid-svg-icons';

export {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAnglesLeft,
  faAnglesRight,
  faAngleUp,
  faArrowDown,
  faArrowRight,
  faArrowRightFromArc,
  faArrowToTop,
  faArrowUp,
  faArrowUpRight,
  faArrowUpRightFromSquare,
  faBadgeCheck,
  faBan,
  faBridge,
  faCaretRight,
  faChartBar,
  faChartPie,
  faChartPieAlt,
  faChartPieSimple,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleBolt,
  faCircleCheck,
  faCircleDown,
  faCircleInfo,
  faCircleMinus,
  faCircleNotch,
  faCirclePause,
  faCirclePlus,
  faCircleQuestion,
  faCircleS,
  faCircleUp,
  faCircleX,
  faCity,
  faClock,
  faClone,
  faClose,
  faCode,
  faCogs,
  faCoins,
  faCommand,
  faCube,
  faDiamond,
  faDiamondExclamation,
  faDollarSign,
  faDown,
  faDownRight,
  faEllipsis,
  faEnvelope,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faEye,
  faFileAlt,
  faFileCode,
  faFilter,
  faFlagAlt,
  faGavel,
  faGlobe,
  faGrid,
  faGrid2,
  faHeart,
  faHexagonCheck,
  faHexagonVerticalNft,
  faHistory,
  faHourglass,
  faInfinity,
  faInfoCircle,
  faLayerGroup,
  faLayerPlus,
  faLeaf,
  faLink,
  faList,
  faListTree,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faPalette,
  faPen,
  faPencil,
  faPersonToPortal,
  faPersonFromPortal,
  faPlay,
  faPlus,
  faQuestionCircle,
  faReceipt,
  faRepeat,
  faSearch,
  faScissors,
  faServer,
  faShieldCheck,
  faSnooze,
  faSpinner,
  faSpinnerThird,
  faSquareInfo,
  faSquarePen,
  faSquareV,
  faStream,
  faSync,
  faTerminal,
  faTimes,
  faTrash,
  faTrophy,
  faUp,
  faUpRight,
  faUser,
  faUserCheck,
  faUserFriends,
  faUserLock,
  faWifiSlash
};
