import {
  faChartBar,
  faCheckCircle,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp as faArrowToTop,
  faAngleUp,
  faAnglesLeft,
  faAnglesRight,
  faArrowDown,
  faArrowRight,
  faArrowUp,
  faArrowUpRightFromSquare as faArrowUpRight,
  faBan,
  faBars as faGrid,
  faBars as faGrid2,
  faCaretRight,
  faChartPie as faChartPieAlt,
  faChartPie,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck as faShieldCheck,
  faCircleCheck,
  faCircleDot as faCircleBolt,
  faCircleDown as faDownRight,
  faCircleDown,
  faCircleInfo,
  faCircleInfo as faSquareInfo,
  faCircleMinus,
  faCircleNotch as faSpinnerThird,
  faCircleNotch,
  faCirclePlus,
  faCircleUp as faUpRight,
  faCircleUp,
  faCity,
  faClock,
  faClone,
  faCode as faTerminal,
  faCode,
  faCogs,
  faCoins,
  faCube,
  faDiamond,
  faDollarSign,
  faEllipsis,
  faEnvelope,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faEye,
  faFileAlt,
  faFileCode,
  faFilter,
  faFlag as faFlagAlt,
  faGlobe,
  faHeart,
  faHistory,
  faHourglass,
  faInfinity,
  faInfoCircle,
  faLayerGroup as faLayerPlus,
  faLayerGroup,
  faLeaf,
  faLink,
  faList as faListTree,
  faList,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faMoon as faSnooze,
  faPalette,
  faPen,
  faPencil,
  faPlay,
  faPlus,
  faQuestionCircle,
  faReceipt,
  faRepeat,
  faSearch,
  faServer,
  faSpinner,
  faSquareCheck as faBadgeCheck,
  faSquareCheck as faHexagonCheck,
  faSquareMinus as faSquareV,
  faSquarePen,
  faSquarePlus as faHexagonVerticalNft,
  faStream,
  faSync,
  faTimes,
  faTrophy,
  faUser,
  faUserCheck,
  faUserFriends,
  faUserLock,
  faWifi as faWifiSlash
} from '@fortawesome/free-solid-svg-icons';

export {
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAnglesLeft,
  faAnglesRight,
  faArrowDown,
  faArrowRight,
  faArrowToTop,
  faArrowUp,
  faArrowUpRight,
  faBadgeCheck,
  faBan,
  faCaretRight,
  faChartBar,
  faChartPie,
  faChartPieAlt,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleBolt,
  faCircleCheck,
  faCircleDown,
  faCircleInfo,
  faSquareInfo,
  faCircleMinus,
  faCircleNotch,
  faCirclePlus,
  faCircleUp,
  faCity,
  faClock,
  faClone,
  faCode,
  faCogs,
  faCoins,
  faCube,
  faDiamond,
  faDollarSign,
  faDownRight,
  faEllipsis,
  faEnvelope,
  faExchange,
  faExchangeAlt,
  faExclamationTriangle,
  faExternalLink,
  faEye,
  faFileAlt,
  faFileCode,
  faFilter,
  faFlagAlt,
  faGlobe,
  faGrid,
  faGrid2,
  faHeart,
  faHexagonCheck,
  faHexagonVerticalNft,
  faHistory,
  faHourglass,
  faInfinity,
  faInfoCircle,
  faLayerGroup,
  faLayerPlus,
  faLeaf,
  faLink,
  faList,
  faListTree,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faPalette,
  faPen,
  faPencil,
  faPlay,
  faPlus,
  faQuestionCircle,
  faReceipt,
  faRepeat,
  faSearch,
  faServer,
  faShieldCheck,
  faSnooze,
  faSpinner,
  faSpinnerThird,
  faSquarePen,
  faSquareV,
  faStream,
  faSync,
  faTerminal,
  faTimes,
  faTrophy,
  faUpRight,
  faUser,
  faUserCheck,
  faUserFriends,
  faUserLock,
  faWifiSlash
};
