const localTestnets = [
  ...(process.env.REACT_APP_WALLET && process.env.NODE_ENV === 'development'
    ? [
        {
          default: false,
          id: 'digital-ocean-toronto',
          name: 'DigitalOcean Toronto',
          nodeUrl: '***REMOVED***',
          elasticUrl: '***REMOVED***',
          refreshRate: 6000,
          numInitCharactersForScAddress: 20,
          decimals: 4,
          denomination: 4,
          gasPrice: 10,
          gasLimit: 1000,
          gasPerDataByte: 1500,
          gasLimitEditable: true,
          economics: true,
          data: true,
          validatorDetails: true,
          faucet: true,
          validatorStatistics: false,
        },
        {
          default: false,
          id: 'ireland',
          name: 'Ireland',
          nodeUrl: 'http://108.129.20.194',
          elasticUrl: 'http://18.200.142.29',
          refreshRate: 6000,
          numInitCharactersForScAddress: 20,
          decimals: 4,
          denomination: 4,
          gasPrice: 10,
          gasLimit: 1000,
          gasPerDataByte: 1500,
          gasLimitEditable: true,
          economics: true,
          data: true,
          validatorDetails: true,
          faucet: true,
          validatorStatistics: false,
        },
      ]
    : []),
  ...(process.env.NODE_ENV === 'development'
    ? [
        {
          default: false,
          id: 'new-api',
          name: 'New API',
          nodeUrl: '***REMOVED***',
          elasticUrl: '***REMOVED***',
          refreshRate: 6000,
          numInitCharactersForScAddress: 20,
          decimals: 4,
          denomination: 18,
          gasPrice: 100000000000000,
          gasLimit: 100000,
          gasPerDataByte: 1500,
          gasLimitEditable: true,
          economics: true,
          data: true,
          validatorDetails: true,
          faucet: false,
          validatorStatistics: true,
        },
        {
          default: true,
          id: 'personal',
          name: 'Personal',
          nodeUrl: 'http://137.116.230.165:8079',
          elasticUrl: 'http://137.116.230.165:9200',
          refreshRate: 6000,
          numInitCharactersForScAddress: 20,
          decimals: 4,
          denomination: 18,
          gasPrice: 100000000000000,
          gasLimit: 100000,
          gasPerDataByte: 1500,
          gasLimitEditable: true,
          economics: true,
          data: true,
          validatorDetails: true,
          faucet: false,
          validatorStatistics: true,
        },
      ]
    : []),
];

export default localTestnets;
