name: deploy-beta

on:
  push:
    branches: [redesign]
  repository_dispatch:
    types: deploy-beta
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: redesign
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build-beta
        env:
          CI: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET_BETA }} --delete
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_ICON_EMOJI: ':globe_with_meridians:'
          SLACK_USERNAME: explorer.elrond.com
          SLACK_MESSAGE: ${{ secrets.AWS_S3_BUCKET_BETA }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
