name: deploy-production

on:
  push:
    branches: [master]
  repository_dispatch:
    types: deploy-production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: 'public/config.production.js'
          target: 'build/config.js'
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PRODUCTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'build'
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_ICON_EMOJI: ':globe_with_meridians:'
          SLACK_USERNAME: explorer.elrond.com
          SLACK_MESSAGE: ${{ secrets.AWS_S3_BUCKET_PRODUCTION }}
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
